name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # هر 5 دقیقه
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/fnaghshin/offmorr-doc.git
          git fetch upstream

      - name: Sync with upstream
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git reset --hard upstream/main
          git push origin main --force
